version: 3 # 使用最新配置版本

on:
  push:
    tags: 
      - 'v*'       # v1.0.0 等语义化版本
      - 'release-*' # release-2025 等自定义标签
      
builds:
  - id: minisocks-local
    binary: minisocks-local
    main: ./cmd/ls-local/main.go
    env:
      - CGO_ENABLED=0
      - GOEXPERIMENT=arenas # Go 1.24 新特性
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

  - id: minisocks-server
    binary: minisocks-server
    main: ./cmd/ls-server/main.go
    env:
      - CGO_ENABLED=0
      - GOEXPERIMENT=arenas
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      darwin: macos

release:
  github:
    owner: beijian128
    name: minisocks
  prerelease: auto