name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 核心权限：允许创建 Release 和上传文件[1](@ref)
      actions: read    # 默认权限，允许基础操作[7](@ref)

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 必须获取完整提交历史[7](@ref)

      - uses: actions/setup-go@v4
        with:
          go-version: '1.24.2' 
          check-latest: false

      - name: Install GoReleaser
        run: go install github.com/goreleaser/goreleaser@latest

      - name: Run GoReleaser
        run: goreleaser release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 确保 Token 注入[6](@ref)